/********************************************************************
* /eth/ethraid5/home/knikolic/LRAnalysis/include/ArDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /eth/ethraid5/home/knikolic/LRAnalysis/include/ArDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableArDictionary();
extern void G__cpp_setup_inheritanceArDictionary();
extern void G__cpp_setup_typetableArDictionary();
extern void G__cpp_setup_memvarArDictionary();
extern void G__cpp_setup_globalArDictionary();
extern void G__cpp_setup_memfuncArDictionary();
extern void G__cpp_setup_funcArDictionary();
extern void G__set_cpp_environmentArDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArAnalysis.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArConfiguration.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArDetector.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArDisplay.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArDMData.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArIO.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArOutput.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArPMT.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArRecoPMT.hh"
#include "/eth/ethraid5/home/knikolic/LRAnalysis/include/ArRun.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ArDictionaryLN_TClass;
extern G__linked_taginfo G__ArDictionaryLN_TBuffer;
extern G__linked_taginfo G__ArDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__ArDictionaryLN_TObject;
extern G__linked_taginfo G__ArDictionaryLN_TString;
extern G__linked_taginfo G__ArDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ArDictionaryLN_TClonesArray;
extern G__linked_taginfo G__ArDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ArDictionaryLN_TQObject;
extern G__linked_taginfo G__ArDictionaryLN_TGWindow;
extern G__linked_taginfo G__ArDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ArDictionaryLN_TFile;
extern G__linked_taginfo G__ArDictionaryLN_TCanvas;
extern G__linked_taginfo G__ArDictionaryLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__ArDictionaryLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ArDictionaryLN_TH1F;
extern G__linked_taginfo G__ArDictionaryLN_TGObject;
extern G__linked_taginfo G__ArDictionaryLN_TGFrame;
extern G__linked_taginfo G__ArDictionaryLN_TGCompositeFrame;
extern G__linked_taginfo G__ArDictionaryLN_TGMainFrame;
extern G__linked_taginfo G__ArDictionaryLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__ArDictionaryLN_TGCheckButton;
extern G__linked_taginfo G__ArDictionaryLN_TGNumberEntry;
extern G__linked_taginfo G__ArDictionaryLN_TArrayI;
extern G__linked_taginfo G__ArDictionaryLN_TF1;
extern G__linked_taginfo G__ArDictionaryLN_TArrayD;
extern G__linked_taginfo G__ArDictionaryLN_TArrayS;
extern G__linked_taginfo G__ArDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ArDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ArDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ArDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ArDictionaryLN_TTree;
extern G__linked_taginfo G__ArDictionaryLN_TBranch;
extern G__linked_taginfo G__ArDictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_ArDetector;
extern G__linked_taginfo G__ArDictionaryLN_ArConfiguration;
extern G__linked_taginfo G__ArDictionaryLN_ArIO;
extern G__linked_taginfo G__ArDictionaryLN_ArPMT;
extern G__linked_taginfo G__ArDictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ArDictionaryLN_ArRun;
extern G__linked_taginfo G__ArDictionaryLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ArDictionaryLN_ArDMData;
extern G__linked_taginfo G__ArDictionaryLN_vectorlEINDEXITEMcOallocatorlEINDEXITEMgRsPgR;
extern G__linked_taginfo G__ArDictionaryLN_reverse_iteratorlEvectorlEINDEXITEMcOallocatorlEINDEXITEMgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ArDictionaryLN_ArAnalysis;
extern G__linked_taginfo G__ArDictionaryLN_TGStatusBar;
extern G__linked_taginfo G__ArDictionaryLN_ArDisplay;
extern G__linked_taginfo G__ArDictionaryLN_ArRecoPMT;
extern G__linked_taginfo G__ArDictionaryLN_ArOutput;

/* STUB derived class for protected member access */
